-- SIENA: Criação de schemas por módulo
-- Cada módulo opera exclusivamente no seu schema

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS escolas;
CREATE SCHEMA IF NOT EXISTS directory;
CREATE SCHEMA IF NOT EXISTS enrollment;
CREATE SCHEMA IF NOT EXISTS academico;
CREATE SCHEMA IF NOT EXISTS avaliacoes;
CREATE SCHEMA IF NOT EXISTS financeiro;
CREATE SCHEMA IF NOT EXISTS provas;
CREATE SCHEMA IF NOT EXISTS vocacional;
CREATE SCHEMA IF NOT EXISTS relatorios;
CREATE SCHEMA IF NOT EXISTS estoque;
CREATE SCHEMA IF NOT EXISTS alimentacao;
CREATE SCHEMA IF NOT EXISTS integracoes;
CREATE SCHEMA IF NOT EXISTS sync;
CREATE SCHEMA IF NOT EXISTS notifications;