"""add escolas module tables

Revision ID: 1efdf44b838c
Revises: 6e0c9914259d
Create Date: 2026-03-11 23:16:21.726444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1efdf44b838c'
down_revision: Union[str, None] = '6e0c9914259d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escola',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo_sige', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), server_default='publica', nullable=False),
    sa.Column('nivel_ensino', sa.String(length=100), server_default='primario', nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('comuna', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sige'),
    schema='escolas'
    )
    op.create_index(op.f('ix_escolas_escola_tenant_id'), 'escola', ['tenant_id'], unique=False, schema='escolas')
    op.create_table('ano_letivo',
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('designacao', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='escolas'
    )
    op.create_index(op.f('ix_escolas_ano_letivo_escola_id'), 'ano_letivo', ['escola_id'], unique=False, schema='escolas')
    op.create_index(op.f('ix_escolas_ano_letivo_tenant_id'), 'ano_letivo', ['tenant_id'], unique=False, schema='escolas')
    op.create_table('configuracao_escola',
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('num_periodos', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('nota_maxima', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('nota_minima_aprovacao', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('configuracao_extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id'),
    schema='escolas'
    )
    op.create_index(op.f('ix_escolas_configuracao_escola_tenant_id'), 'configuracao_escola', ['tenant_id'], unique=False, schema='escolas')
    op.create_table('infraestrutura',
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), server_default='sala_aula', nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='operacional', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='escolas'
    )
    op.create_index(op.f('ix_escolas_infraestrutura_escola_id'), 'infraestrutura', ['escola_id'], unique=False, schema='escolas')
    op.create_index(op.f('ix_escolas_infraestrutura_tenant_id'), 'infraestrutura', ['tenant_id'], unique=False, schema='escolas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escolas_infraestrutura_tenant_id'), table_name='infraestrutura', schema='escolas')
    op.drop_index(op.f('ix_escolas_infraestrutura_escola_id'), table_name='infraestrutura', schema='escolas')
    op.drop_table('infraestrutura', schema='escolas')
    op.drop_index(op.f('ix_escolas_configuracao_escola_tenant_id'), table_name='configuracao_escola', schema='escolas')
    op.drop_table('configuracao_escola', schema='escolas')
    op.drop_index(op.f('ix_escolas_ano_letivo_tenant_id'), table_name='ano_letivo', schema='escolas')
    op.drop_index(op.f('ix_escolas_ano_letivo_escola_id'), table_name='ano_letivo', schema='escolas')
    op.drop_table('ano_letivo', schema='escolas')
    op.drop_index(op.f('ix_escolas_escola_tenant_id'), table_name='escola', schema='escolas')
    op.drop_table('escola', schema='escolas')
    # ### end Alembic commands ###
