"""create identity tables

Revision ID: 6e0c9914259d
Revises: 
Create Date: 2026-03-10 23:08:16.759560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0c9914259d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papel',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('permissoes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='identity'
    )
    op.create_table('tenant',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ativo', nullable=False),
    sa.Column('plano', sa.String(length=50), server_default='basico', nullable=False),
    sa.Column('licenca_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuracao', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('utilizador',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=30), server_default='local', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mfa_segredo', sa.String(length=255), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_utilizador_tenant_id'), 'utilizador', ['tenant_id'], unique=False, schema='identity')
    op.create_table('utilizador_papel',
    sa.Column('utilizador_id', sa.UUID(), nullable=False),
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('escopo', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['identity.papel.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenant.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['identity.utilizador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilizador_papel', schema='identity')
    op.drop_index(op.f('ix_identity_utilizador_tenant_id'), table_name='utilizador', schema='identity')
    op.drop_table('utilizador', schema='identity')
    op.drop_table('tenant', schema='identity')
    op.drop_table('papel', schema='identity')
    # ### end Alembic commands ###
